#theme
#theme: jekyll-theme-hacker
remote_theme: TaylanTatl/Moon

#site details
title: dalemazza github io
name: Dale Marriott
description: My journey from scrub to OSCP
assets: https://raw.githubusercontent.com/dalemazza/dalemazza.github.io/master/assets/
avatar: https://raw.githubusercontent.com/dalemazza/dalemazza.github.io/master/assets/avatar.png


#markdown
markdown: kramdown
