#theme
theme: jekyll-theme-hacker

#site details
title: dalemazza github io
name: Dale Marriott
description: My journey from scrub to OSCP
assets: https://raw.githubusercontent.com/dalemazza/dalemazza.github.io/master/assets/


#markdown
markdown: kramdown
