theme: jekyll-theme-hacker
name: Dale Marriott
description: My journey from scrub to OSCP
url: "https://dalemazza.github.io/"
markdown: kramdown

github:
  about: https://dalemazza.github.io/about


#footerlinks
footer-links:
  github: dalemazza
  linkedin: dale marriott
